version: '2.4'

services:

    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        env_file: .env
        depends_on:
          - postgres
        ports:
          - "8000:8000"
        volumes:
          - ./src:/home/php/src

    postgres:
        image: postgres:12.2
        environment:
            - "POSTGRES_USER=${DB_USER}"
            - "POSTGRES_DB=${DB_NAME}"
            - "POSTGRES_PASSWORD=${DB_PASS}"